"""Create initial database

Revision ID: fb99f249208d
Revises: 
Create Date: 2026-09-02 12:40:10.198824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb99f249208d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(display_name)) > 0', name='app_users_display_name_present'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_subject', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(provider)) > 0', name='auth_identity_provider_present'),
    sa.CheckConstraint('length(trim(provider_subject)) > 0', name='auth_identity_subject_present'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='auth_identity_provider_subject_key')
    )
    op.create_table('households',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('default_timezone', sa.Text(), server_default='UTC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(default_timezone)) > 0', name='households_timezone_present'),
    sa.CheckConstraint('length(trim(name)) > 0', name='households_name_present'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_memberships',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'active' AND left_at IS NULL) OR (status = 'inactive' AND left_at IS NOT NULL)", name='membership_status_matches_left_at'),
    sa.CheckConstraint("role IN ('member', 'administrator')", name='membership_role_valid'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='membership_status_valid'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('household_id', 'user_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('before_values', sa.JSON(), nullable=True),
    sa.Column('after_values', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'delete')", name='audit_events_action_valid'),
    sa.CheckConstraint('before_values IS NOT NULL OR after_values IS NOT NULL', name='audit_events_values_present'),
    sa.CheckConstraint('length(trim(entity_type)) > 0', name='audit_events_entity_type_present'),
    sa.ForeignKeyConstraint(['household_id', 'actor_user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='audit_events_actor_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('audit_events_household_occurred_at_idx', 'audit_events', ['household_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('integration_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(trim(client_name)) > 0', name='integration_client_name_present'),
    sa.CheckConstraint('length(trim(idempotency_key)) > 0', name='integration_key_present'),
    sa.CheckConstraint('length(trim(operation)) > 0', name='integration_operation_present'),
    sa.CheckConstraint('response_status IS NULL OR response_status BETWEEN 100 AND 599', name='integration_response_status_valid'),
    sa.ForeignKeyConstraint(['household_id', 'actor_user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='integration_requests_actor_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_user_id', 'client_name', 'idempotency_key', name='integration_requests_idempotency_key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), server_default='other', nullable=False),
    sa.Column('lifecycle_status', sa.Text(), server_default='active', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(lifecycle_status = 'active' AND completed_at IS NULL AND cancelled_at IS NULL) OR (lifecycle_status = 'completed' AND completed_at IS NOT NULL AND cancelled_at IS NULL) OR (lifecycle_status = 'cancelled' AND completed_at IS NULL AND cancelled_at IS NOT NULL)", name='tasks_lifecycle_timestamps_match'),
    sa.CheckConstraint("lifecycle_status IN ('active', 'completed', 'cancelled')", name='tasks_lifecycle_status_valid'),
    sa.CheckConstraint('estimated_duration_minutes IS NULL OR estimated_duration_minutes > 0', name='tasks_estimated_duration_positive'),
    sa.CheckConstraint('length(trim(category)) > 0', name='tasks_category_present'),
    sa.CheckConstraint('length(trim(title)) > 0', name='tasks_title_present'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='tasks_creator_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id', 'parent_task_id'], ['tasks.household_id', 'tasks.id'], name='tasks_parent_task_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'id', name='tasks_household_id_id_key')
    )
    op.create_index('tasks_household_status_idx', 'tasks', ['household_id', 'lifecycle_status'], unique=False)
    op.create_index('tasks_parent_task_idx', 'tasks', ['household_id', 'parent_task_id'], unique=False, postgresql_where=sa.text('parent_task_id IS NOT NULL'))
    op.create_table('time_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('block_kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(block_kind = 'planned' AND status IN ('planned', 'completed', 'cancelled')) OR (block_kind = 'actual' AND status = 'completed')", name='time_blocks_kind_matches_status'),
    sa.CheckConstraint("block_kind IN ('planned', 'actual')", name='time_blocks_kind_valid'),
    sa.CheckConstraint("status IN ('planned', 'completed', 'cancelled')", name='time_blocks_status_valid'),
    sa.CheckConstraint('ends_at > starts_at', name='time_blocks_time_range_valid'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='time_blocks_creator_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'id', name='time_blocks_household_id_id_key')
    )
    op.create_index('time_blocks_household_starts_at_idx', 'time_blocks', ['household_id', 'starts_at'], unique=False)
    op.create_table('recurrence_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('frequency_interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'monthly', 'yearly')", name='recurrence_rules_frequency_valid'),
    sa.CheckConstraint('day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31', name='recurrence_rules_day_of_month_valid'),
    sa.CheckConstraint('days_of_week IS NULL OR days_of_week <@ ARRAY[0,1,2,3,4,5,6]::smallint[]', name='recurrence_rules_weekdays_valid'),
    sa.CheckConstraint('ends_on IS NULL OR ends_on >= starts_on', name='recurrence_rules_dates_valid'),
    sa.CheckConstraint('frequency_interval > 0', name='recurrence_rules_interval_positive'),
    sa.ForeignKeyConstraint(['household_id', 'task_id'], ['tasks.household_id', 'tasks.id'], name='recurrence_rules_task_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'id', name='recurrence_rules_household_id_id_key'),
    sa.UniqueConstraint('task_id', 'id', name='recurrence_rules_task_id_id_key'),
    sa.UniqueConstraint('task_id', name='recurrence_rules_task_id_key')
    )
    op.create_table('task_participants',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id', 'task_id'], ['tasks.household_id', 'tasks.id'], name='task_participants_task_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id', 'user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='task_participants_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id']),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_index('task_participants_household_user_idx', 'task_participants', ['household_id', 'user_id'], unique=False)
    op.create_table('time_block_participants',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('time_block_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id', 'time_block_id'], ['time_blocks.household_id', 'time_blocks.id'], name='time_block_participants_block_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id', 'user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='time_block_participants_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id']),
    sa.PrimaryKeyConstraint('time_block_id', 'user_id')
    )
    op.create_index('time_block_participants_household_user_idx', 'time_block_participants', ['household_id', 'user_id'], unique=False)
    op.create_table('task_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('recurrence_rule_id', sa.Uuid(), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('lifecycle_status', sa.Text(), server_default='active', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(lifecycle_status = 'completed' AND completed_at IS NOT NULL) OR (lifecycle_status <> 'completed' AND completed_at IS NULL)", name='task_instances_completion_timestamp_matches'),
    sa.CheckConstraint("lifecycle_status IN ('active', 'completed', 'skipped', 'cancelled')", name='task_instances_lifecycle_status_valid'),
    sa.ForeignKeyConstraint(['household_id', 'task_id'], ['tasks.household_id', 'tasks.id'], name='task_instances_task_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id', 'recurrence_rule_id'], ['recurrence_rules.task_id', 'recurrence_rules.id'], name='task_instances_recurrence_rule_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'id', name='task_instances_household_id_id_key'),
    sa.UniqueConstraint('task_id', 'id', name='task_instances_task_id_id_key'),
    sa.UniqueConstraint('task_id', 'occurrence_date', name='task_instances_task_date_key')
    )
    op.create_index('task_instances_household_date_idx', 'task_instances', ['household_id', 'occurrence_date'], unique=False)
    op.create_table('completion_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('task_instance_id', sa.Uuid(), nullable=True),
    sa.Column('time_block_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Text(), server_default='other', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_override_minutes', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(started_at IS NULL AND ended_at IS NULL) OR (started_at IS NOT NULL AND ended_at IS NOT NULL AND ended_at > started_at)', name='completion_records_time_range_valid'),
    sa.CheckConstraint('duration_override_minutes IS NOT NULL OR (started_at IS NOT NULL AND ended_at IS NOT NULL) OR time_block_id IS NOT NULL', name='completion_records_duration_source_present'),
    sa.CheckConstraint('duration_override_minutes IS NULL OR duration_override_minutes > 0', name='completion_records_override_positive'),
    sa.CheckConstraint('length(trim(category)) > 0', name='completion_records_category_present'),
    sa.CheckConstraint('task_instance_id IS NULL OR task_id IS NOT NULL', name='completion_records_instance_requires_task'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='completion_records_creator_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id', 'task_id'], ['tasks.household_id', 'tasks.id'], name='completion_records_task_fkey'),
    sa.ForeignKeyConstraint(['household_id', 'time_block_id'], ['time_blocks.household_id', 'time_blocks.id'], name='completion_records_time_block_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id', 'task_instance_id'], ['task_instances.task_id', 'task_instances.id'], name='completion_records_instance_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'id', name='completion_records_household_id_id_key')
    )
    op.create_index('completion_records_household_completed_at_idx', 'completion_records', ['household_id', 'completed_at'], unique=False)
    op.create_table('task_instance_participants',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('task_instance_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id', 'task_instance_id'], ['task_instances.household_id', 'task_instances.id'], name='task_instance_participants_instance_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id', 'user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='task_instance_participants_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id']),
    sa.PrimaryKeyConstraint('task_instance_id', 'user_id')
    )
    op.create_index('task_instance_participants_household_user_idx', 'task_instance_participants', ['household_id', 'user_id'], unique=False)
    op.create_table('time_block_tasks',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('time_block_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('task_instance_id', sa.Uuid(), nullable=True),
    sa.Column('planned_minutes', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('planned_minutes IS NULL OR planned_minutes > 0', name='time_block_tasks_planned_minutes_positive'),
    sa.CheckConstraint('sort_order >= 0', name='time_block_tasks_sort_order_valid'),
    sa.ForeignKeyConstraint(['household_id', 'task_id'], ['tasks.household_id', 'tasks.id'], name='time_block_tasks_task_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id', 'time_block_id'], ['time_blocks.household_id', 'time_blocks.id'], name='time_block_tasks_block_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id', 'task_instance_id'], ['task_instances.task_id', 'task_instances.id'], name='time_block_tasks_instance_fkey'),
    sa.PrimaryKeyConstraint('time_block_id', 'task_id')
    )
    op.create_table('completion_record_participants',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('completion_record_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id', 'completion_record_id'], ['completion_records.household_id', 'completion_records.id'], name='completion_participants_record_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id', 'user_id'], ['household_memberships.household_id', 'household_memberships.user_id'], name='completion_participants_membership_fkey'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id']),
    sa.PrimaryKeyConstraint('completion_record_id', 'user_id')
    )
    op.create_index('completion_participants_household_user_idx', 'completion_record_participants', ['household_id', 'user_id'], unique=False)
    # ### end Alembic commands ###

    # PostgreSQL protections that SQLAlchemy models cannot express directly.
    op.execute("""
        CREATE FUNCTION validate_household_timezone()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_timezone_names WHERE name = NEW.default_timezone
            ) THEN
                RAISE EXCEPTION 'invalid household timezone: %', NEW.default_timezone;
            END IF;
            RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER households_validate_timezone
        BEFORE INSERT OR UPDATE OF default_timezone ON households
        FOR EACH ROW EXECUTE FUNCTION validate_household_timezone()
    """)

    op.execute("""
        CREATE FUNCTION prevent_task_hierarchy_cycle()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.parent_task_id IS NULL THEN
                RETURN NEW;
            END IF;
            IF NEW.parent_task_id = NEW.id THEN
                RAISE EXCEPTION 'a task cannot be its own parent';
            END IF;
            IF EXISTS (
                WITH RECURSIVE ancestors (id, parent_task_id) AS (
                    SELECT id, parent_task_id
                    FROM tasks
                    WHERE household_id = NEW.household_id
                      AND id = NEW.parent_task_id
                    UNION
                    SELECT parent.id, parent.parent_task_id
                    FROM tasks AS parent
                    JOIN ancestors AS child ON parent.id = child.parent_task_id
                    WHERE parent.household_id = NEW.household_id
                )
                SELECT 1 FROM ancestors WHERE id = NEW.id
            ) THEN
                RAISE EXCEPTION 'task hierarchy cannot contain a cycle';
            END IF;
            RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER tasks_prevent_hierarchy_cycle
        BEFORE INSERT OR UPDATE OF parent_task_id, household_id ON tasks
        FOR EACH ROW EXECUTE FUNCTION prevent_task_hierarchy_cycle()
    """)

    op.execute("""
        CREATE FUNCTION prevent_audit_event_changes()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'audit events are append-only';
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER audit_events_are_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_event_changes()
    """)

    op.execute("""
        CREATE VIEW completion_record_durations AS
        SELECT
            completion.id AS completion_record_id,
            completion.household_id,
            COALESCE(
                completion.duration_override_minutes,
                CASE
                    WHEN completion.started_at IS NOT NULL AND completion.ended_at IS NOT NULL
                        THEN ceil(extract(epoch FROM (
                            completion.ended_at - completion.started_at
                        )) / 60.0)::bigint
                    WHEN time_block.id IS NOT NULL
                        THEN ceil(extract(epoch FROM (
                            time_block.ends_at - time_block.starts_at
                        )) / 60.0)::bigint
                END
            ) AS duration_minutes
        FROM completion_records AS completion
        LEFT JOIN time_blocks AS time_block ON time_block.id = completion.time_block_id
    """)
    op.execute("""
        CREATE VIEW member_contribution_durations AS
        SELECT
            completion.household_id,
            participant.user_id,
            date_trunc(
                'day',
                completion.completed_at AT TIME ZONE household.default_timezone
            )::date AS contribution_day,
            sum(duration.duration_minutes)::bigint AS duration_minutes
        FROM completion_records AS completion
        JOIN completion_record_participants AS participant
            ON participant.completion_record_id = completion.id
        JOIN completion_record_durations AS duration
            ON duration.completion_record_id = completion.id
        JOIN households AS household
            ON household.id = completion.household_id
        GROUP BY
            completion.household_id,
            participant.user_id,
            date_trunc(
                'day',
                completion.completed_at AT TIME ZONE household.default_timezone
            )::date
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW member_contribution_durations")
    op.execute("DROP VIEW completion_record_durations")
    op.execute("DROP FUNCTION prevent_audit_event_changes() CASCADE")
    op.execute("DROP FUNCTION prevent_task_hierarchy_cycle() CASCADE")
    op.execute("DROP FUNCTION validate_household_timezone() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('completion_participants_household_user_idx', table_name='completion_record_participants')
    op.drop_table('completion_record_participants')
    op.drop_table('time_block_tasks')
    op.drop_index('task_instance_participants_household_user_idx', table_name='task_instance_participants')
    op.drop_table('task_instance_participants')
    op.drop_index('completion_records_household_completed_at_idx', table_name='completion_records')
    op.drop_table('completion_records')
    op.drop_index('task_instances_household_date_idx', table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index('time_block_participants_household_user_idx', table_name='time_block_participants')
    op.drop_table('time_block_participants')
    op.drop_index('task_participants_household_user_idx', table_name='task_participants')
    op.drop_table('task_participants')
    op.drop_table('recurrence_rules')
    op.drop_index('time_blocks_household_starts_at_idx', table_name='time_blocks')
    op.drop_table('time_blocks')
    op.drop_index('tasks_parent_task_idx', table_name='tasks', postgresql_where=sa.text('parent_task_id IS NOT NULL'))
    op.drop_index('tasks_household_status_idx', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('integration_requests')
    op.drop_index('audit_events_household_occurred_at_idx', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('household_memberships')
    op.drop_table('households')
    op.drop_table('auth_identities')
    op.drop_table('app_users')
    # ### end Alembic commands ###
